### ISSUE TITLE
Is there a documentation how to use this as a module in a custom CLI node app?

### ISSUE THREAD

**Issue by carstenmichel** [rastapasta/mapscii#78] opened 2019-12-04 17:18 UTC
I would like to use mapscii as a module in a standalone CLI client to display map information. Is there some documentation available for this planned or ready?
Many thanks

**Comment by jaller94** [comment] 2019-12-04 19:01
Uh, sounds interesting. What are you building?
Currently not available but planned (without any timeline).
A JavaScript developer should have a fairly easy time building a modified CLI application with the code available in [src/Mapscii.js](https://github.com/rastapasta/mapscii/blob/master/src/Mapscii.js).

The most recent statement by the author can be found here:
https://github.com/rastapasta/mapscii/issues/27#issuecomment-544001117

I'm closing this as a duplicate of #66.

**Closed by jaller94** 2019-12-04 19:01 UTC
