### ISSUE TITLE
Can't zoom more than approximately 2.0x in WSL

### ISSUE THREAD

**Issue by KnightChaser** [rastapasta/mapscii#150] opened 2024-10-28 06:27 UTC
**Steps to reproduce**

My environment is `Ubuntu 22.04.5 LTS on Windows 10 x86_64`, `5.15.153.1-microsoft-standard-WSL2`
Install the newest `mapscii` via `snap` command. (In my environment)

For more context about my environment, here I attach the output of the command `neofetch`
![image](https://github.com/user-attachments/assets/a12ce33f-c726-4f21-b73a-186178a86219)

**Current behavior**

Open `mapscii` and gradually zoom toward any position. When I zoom in more than (approximately) 2.0x, it suddenly shows a blackout screen like the picture below.
![image](https://github.com/user-attachments/assets/136315e7-0159-4128-84bf-aed240298b23)

I don't know exactly why this was occurred. Sometimes, when I zoom out again so the magnification rate becomes smaller than about 2.0x, it returns to normal. Or, it pauses working and crashes.

And  I could check the following exception log was also printed after that crash.
```
renderer is busyError: Unimplemented type: 4
    at Pbf.skip (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/pbf/index.js:211:20)
    at Pbf.readFields (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/pbf/index.js:46:45)
    at new VectorTile (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/@mapbox/vector-tile/lib/vectortile.js:8:23)
    at Tile._loadTile (/snap/mapscii/14/lib/node_modules/mapscii/src/Tile.js:33:17)
    at /snap/mapscii/14/lib/node_modules/mapscii/src/Tile.js:24:19
```

The one notable thing is I encountered this issue that hasn't happened before, I encountered such a problem first today.

**Expected behavior**

The zoomed map should be rendered properly, even though there might be a delay due to the rendering process.

**Comment by jaller94** [comment] 2024-11-02 18:41
Thank you for taking the time to report this.
Yes, there are a few issue with the current map data and renderer.

I'm going to close this as a duplicate of https://github.com/rastapasta/mapscii/issues/87. 
I know that there are more issues listed, but to keep things simple and because we hobby developers wish for a larger maintainance update, it's currently best to close this issue in my opinion.

**Closed as not planned by jaller94** 2024-11-02 18:41 UTC
